 - Numpy
 - Array operations
 - Slicing
 - Functions
 - Matrix
 - Pandas
 - Series			

In [2]:
import numpy as np

In [5]:
arr1 = np.arange(5)
arr1

array([0, 1, 2, 3, 4])

In [12]:
arr2 = np.array([4,5,6.58,7,8])
arr2[1].dtype

dtype('float64')

In [10]:
a1 = np.arange(10)
a1[2].dtype

dtype('int32')

In [14]:
a1 = np.arange(12).reshape(4,3)
a1

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [16]:
l1 = [i for i in range(10) if i %2==0]
l1

[0, 2, 4, 6, 8]

In [29]:
a2 = np.array(l1)
a2
a4 = np.array([1,2,3,4,5])

In [22]:
a3 = np.random.randn(5)
a3

array([-1.39498007e-04, -1.47464533e+00, -1.15800776e+00,  1.04522299e+00,
        6.82648374e-01])

In [30]:
a2+a4

array([ 1,  4,  7, 10, 13])

In [31]:
a5 = np.add(a2,a4)
a5

array([ 1,  4,  7, 10, 13])

In [36]:
for i in range(len(a5)):
    print(a5[i])

1
4
7
10
13


In [38]:
a1

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [43]:
a1[2][1]

7

In [46]:
a1

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [52]:
a6 = np.array(
    [[1,2,3,4],
    [5,6,7,8],
    [23,4,5,6]]
)
a6

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [23,  4,  5,  6]])

In [66]:
a6.max()
a6.min()
round(a6.mean(),5)

6.16667

In [68]:
a6.diagonal()

array([1, 6, 5])

In [69]:
a6.transpose()

array([[ 1,  5, 23],
       [ 2,  6,  4],
       [ 3,  7,  5],
       [ 4,  8,  6]])

In [71]:
matrix = a6
matrix

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [23,  4,  5,  6]])

In [73]:
# Create 2 matrix of different dimentions
# Matrix Operations - Addition / Subtraction / Multiplication / Division
# Matrix /arrays of zeros/ones

In [ ]:
input("Enter row - ")
input("Enter column - ")

In [5]:
import numpy as np
matrix1 = np.array([[1,2,3],
                    [3,4,5]])
matrix1

matrix2 = np.array([[1,2],
                    [3,4],
                    [5,6]])
matrix2

array([[1, 2],
       [3, 4],
       [5, 6]])

In [16]:
# Multiplication
# col of M1 = rows of M2
for i in range(len(matrix1)):
    print("Inside Row loop")
    for j in range(matrix1.shape[1]):
        print("Inside Col Loop")
        print(matrix1[i][j])
    

Inside Row loop
Inside Col Loop
1
Inside Col Loop
2
Inside Col Loop
3
Inside Row loop
Inside Col Loop
3
Inside Col Loop
4
Inside Col Loop
5


In [12]:
matrix1.shape[1]

3